version: '3.5'

networks:
   web-app-net:
       name: my-web-app-net
       #driver: overlay
       driver: bridge

volumes:
   mysql-db-storage:
   activemq-storage:
   redis-inmemory-storage:

services:
   mysql-db:
      image: mysql:8.0.13
      environment:
          MYSQL_DATABASE: testDB
          MYSQL_ROOT_PASSWORD: root@123
      ports:
          - 3317:3306
      networks:
          - web-app-net
      volumes:
          - mysql-db-storage:/var/lib/mysql

   activemq:
      image: webcenter/activemq
      ports:
        - 8161:8161
        - 61616:61616
        - 61613:61613
      environment:
        - ACTIVEMQ_MIN_MEMORY=512
        - ACTIVEMQ_MAX_MEMORY=2048
        - ACTIVEMQ_ADMIN_LOGIN=admin
        - ACTIVEMQ_ADMIN_PASSWORD=admin
      restart: on-failure
      networks:
        - web-app-net
      volumes:
        - activemq-storage:/var/log/activemq

   redis:
      image: redis:latest
      ports:
         - 6379:6379
      networks:
         - web-app-net
      volumes:
         - redis-inmemory-storage:/data

   webapp:
      image: event-driven-microservice-starter:1.0
      build:
         context: .
         #dockerfile: Dockerfile
         dockerfile: Dockerfile-embedded
      environment:
         app.db.name: testDB
         app.db.host: mysql-db
         app.db.port: 3306
         app.db.password: root@123
         app.redis.host: redis
         app.redis.port: 6379
         app.activemq.host: activemq
         app.activemq.port: 61616
         app.activemq.schema: tcp://
         app.activemq.username: admin
         app.activemq.password: admin
         management.endpoints.web.exposure.include: health,metrics,httptrace,prometheus
      ports:
         - 8081:8080
      depends_on:
         - mysql-db
         - redis
         - activemq
      restart: on-failure
      networks:
         - web-app-net